gridWorkingDir:		workingdir
gridOutputDir:		outputdir_13c_pass4_v2_4run_noClusCut
aliROOTVersion:		v5-09-23-1
aliPhysicsVersion:	vAN-20180222-1
gridDataDir:		/alice/data/2013/LHC13c
dataPattern:		/pass4/*/AliESDs.root
runPrefix:              000
runNumber:		[195677, 195675, 195673, 195644]
emcalCorrection:	emcal_correction.yaml
skimTrackMinPt:		4.0